parser.h: Including missing <cstdint>
- Update copyright year

- This is needed from gcc-13+ see [1]

- Fixes

../git/framework/platform/parser.h:282:43: error: 'uint32_t' does not name a type
  282 |                 *type       = static_cast<uint32_t>(number);
      |                                           ^~~~~~~~
../git/framework/platform/parser.h:21:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?

[1] https://www.gnu.org/software/gcc/gcc-13/porting_to.html

Signed-off-by: Khem Raj <raj.khem@gmail.com>

s